### ISSUE TITLE
Translator error

### ISSUE THREAD

**Issue by Oumbra** [Micha-ohne-el/transl#5]
For a few days now, the "/translate" commands and the "translate for me" option have not been working and are ending with an error.

Example using command "/translate", few one or two minutes : 
![image](https://github.com/Micha-ohne-el/transl/assets/37836998/20d23054-7fcd-407c-8ed3-238883aa695a)

Example using "translate for me" :
![image](https://github.com/Micha-ohne-el/transl/assets/37836998/51034d25-d856-4446-9fc4-a3a501eae1d4)

Server configurations:
![image](https://github.com/Micha-ohne-el/transl/assets/37836998/13635f75-55e1-413c-9608-075860f731b7)

**Comment by SimplyMika** [comment]
Hi there, thanks for submitting a report!

This month's translation limit has been reached, which is why the bot stopped working.

I've now increased the monthly limit, and the bot works again, but I can't keep doing this as it's getting too expensive. I will add a better error message for this eventually though.

TransL now costs me 40 EUR per month in DeepL subscription costs, so in case you want to support me, you can donate some money on [Ko-Fi](https://ko-fi.com/micha). I'd appreciate it a lot, but no pressure!
